#!/usr/bin/env bash
# manages a process

FILE="/var/run/my_process.pid"

case $1 in
  "start")
    ./manage_my_process
    echo $$ > $FILE
    echo "manage_my_process started"
  ;;
  "stop")
    rm $FILE
    echo "manage_my_process stopped"
  ;;
  "restart")
    pkill -f manage_my_process
    rm $FILE
    ./manage_my_process
    echo $$ > $FILE
    echo "manage_my_process restarted"
  ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
  ;;
esac
