#!/usr/bin/env bash
# prints the clock
declare -i hour
while [[ $hour -le 12 ]]
do
  echo "Hour: $((hour))"
  declare -i minute=1
  while [[ $minute -lt 60 ]]
  do
    echo $minute
    minute+=1
  done
  hour+=1
done
